In [1]:
import os
os.getcwd()

'C:\\Users\\Daniel\\AppData\\Local\\Programs\\Python'

In [3]:
os.chdir('C:/Users/Daniel/Desktop/Data Sets')
os.getcwd()

'C:\\Users\\Daniel\\Desktop\\Data Sets'

In [4]:
import numpy as np
import pandas as pd
data1=pd.read_csv("bikebuyer1.csv")
data1

,ID,Marital Status,Gender,Yearly Income,Children,Education,Occupation,Home Owner,Cars,Commute Distance,Region,Age,Bike Buyer
0,22711.0,Single,Male,30000,0.0,Partial College,Clerical,No,1,1.0,Europe,33,Yes
1,13555.0,Married,Female,40000,0.0,Graduate Degree,Clerical,Yes,0,1.0,Europe,37,Yes
2,NaN,Married,Male,160000,5.0,Partial College,Professional,No,3,2.0,Europe,55,No
3,2.0,Single,Male,160000,0.0,Graduate Degree,Management,Yes,2,5.0,Pacific,47,No
4,25410.0,NaN,Female,70000,2.0,Bachelors,Skilled Manual,No,1,1.0,North America,38,Yes
5,4.0,Married,NaN,120000,2.0,Bachelors,Management,Yes,3,1.0,North America,40,No
6,15756.0,Single,Female,70000,0.0,High School,Professional,Yes,2,NaN,Pacific,49,Yes
7,11085.0,Single,Female,60000,0.0,High School,Professional,No,2,1.0,North America,49,No
8,17974.0,NaN,Female,0,NaN,Bachelors,Clerical,Yes,0,10.0,Europe,38,Yes
9,21008.0,Single,Female,20000,1.0,Partial College,Manual,No,0,1.0,Europe,46,Yes
10,28985.0,Single,Male,50000,0.0,Bachelors,Management,No,2,2.0,North America,64,No
11,11087.0,Married,Female,70000,2.0,Partial College,Professional,No,0,11.0,North America,49,No
12,20434.0,Single,NaN,60000,0.0,Partial College,Skilled Manual,No,2,1.0,North America,31,Yes
13,14902.0,NaN,Female,40000,0.0,Partial College,Clerical,Yes,1,1.0,North America,50,Yes
14,11091.0,Married,Male,90000,0.0,Partial College,Professional,Yes,1,1.0,North America,49,No
15,11094.0,Single,Male,70000,0.0,Partial College,Skilled Manual,No,1,1.0,Pacific,44,No
16,18568.0,Single,Female,50000,2.0,Bachelors,Skilled Manual,Yes,1,2.0,North America,39,Yes
17,16366.0,Married,Female,40000,0.0,Partial College,Clerical,Yes,1,1.0,North America,51,Yes
18,20768.0,Single,Male,0,0.0,Partial College,Clerical,Yes,1,2.0,North America,48,Yes
19,11098.0,NaN,Female,60000,0.0,Partial College,Skilled Manual,No,1,6.0,Pacific,45,No
20,18269.0,Single,Female,60000,2.0,Bachelors,Professional,Yes,2,1.0,Pacific,43,Yes
21,11102.0,Single,NaN,80000,5.0,Bachelors,Professional,Yes,4,12.0,Pacific,41,No
22,11113.0,Married,Male,70000,4.0,Bachelors,Professional,Yes,2,1.0,Pacific,44,No
23,26529.0,NaN,Female,70000,0.0,Graduate Degree,Professional,Yes,0,NaN,North America,37,Yes
24,11114.0,Single,Female,70000,4.0,Partial College,Skilled Manual,Yes,2,1.0,Pacific,44,No
25,23612.0,Single,Female,90000,0.0,Partial College,Professional,No,2,1.0,Europe,62,Yes
26,11115.0,Married,Male,70000,4.0,Partial College,Skilled Manual,Yes,2,1.0,Pacific,44,No
27,11116.0,Married,Male,70000,4.0,Partial College,Skilled Manual,Yes,2,9.0,Pacific,44,No
28,11118.0,Single,Male,80000,NaN,Partial College,Skilled Manual,No,1,5.0,Pacific,49,No
29,19441.0,Single,Male,40000,0.0,Graduate Degree,Clerical,Yes,0,1.0,Europe,37,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6967,22779.0,Married,Male,60000,1.0,Partial College,Professional,Yes,2,2.0,North America,54,No
6968,22781.0,Married,Male,70000,2.0,Partial College,Professional,Yes,1,1.0,North America,55,No
6969,22783.0,Married,Male,70000,1.0,Partial High School,Skilled Manual,Yes,2,1.0,North America,54,No
6970,22786.0,Married,Male,70000,1.0,Partial High School,Skilled Manual,Yes,3,2.0,North America,54,No
6971,22792.0,Married,Male,70000,3.0,Partial College,Professional,Yes,1,7.0,North America,53,No
6972,22793.0,Single,Male,70000,3.0,Partial College,Professional,Yes,1,8.0,North America,53,No
6973,22794.0,Married,Female,130000,4.0,Partial College,Professional,Yes,1,9.0,Europe,48,No
6974,22795.0,Married,Female,110000,4.0,Partial College,Professional,Yes,3,2.0,Europe,49,No
6975,22796.0,Married,Male,110000,4.0,Partial College,Professional,No,3,3.0,Europe,49,No
6976,22798.0,Married,Female,150000,3.0,High School,Professional,Yes,4,5.0,Europe,49,No
6977,22799.0,Married,Female,120000,4.0,Partial High School,Professional,No,4,6.0,Europe,50,No
6978,22801.0,Married,Female,110000,4.0,Partial College,Professional,Yes,4,7.0,Europe,51,No
6979,22802.0,Single,Female,120000,4.0,Partial High School,Professional,Yes,4,1.0,Europe,51,No
6980,22804.0,Married,Female,80000,1.0,Partial College,Professional,Yes,2,2.0,Europe,51,No
6981,22805.0,Married,Female,80000,0.0,Bachelors,Management,Yes,2,1.0,Europe,62,No
6982,22806.0,Married,Female,90000,0.0,Partial College,Professional,Yes,2,1.0,Europe,62,No
6983,22807.0,Married,Female,130000,4.0,Bachelors,Management,Yes,4,2.0,Europe,62,No
6984,22809.0,Married,Male,80000,0.0,Partial College,Professional,Yes,2,7.0,Europe,61,No
6985,22811.0,Married,Male,110000,4.0,Bachelors,Management,Yes,4,8.0,Europe,61,No
6986,22812.0,Married,Female,120000,4.0,Bachelors,Management,Yes,4,9.0,Europe,61,No
6987,22813.0,Married,Male,130000,4.0,Bachelors,Management,Yes,4,2.0,Europe,61,No
6988,22814.0,Married,Male,100000,3.0,Bachelors,Management,Yes,4,3.0,Europe,60,No
6989,22815.0,Married,Female,100000,4.0,Bachelors,Management,Yes,1,5.0,Europe,60,No
6990,22818.0,Married,Female,150000,4.0,Graduate Degree,Management,Yes,4,6.0,Europe,60,No
6991,22819.0,Married,Female,80000,2.0,Partial College,Professional,Yes,2,7.0,Europe,53,No
6992,22820.0,Married,Male,100000,4.0,High School,Professional,Yes,3,1.0,Europe,52,No
6993,22821.0,Married,Female,130000,4.0,Partial College,Professional,Yes,4,2.0,Europe,52,No
6994,22823.0,Married,Female,160000,5.0,Bachelors,Management,Yes,2,1.0,Europe,53,No
6995,22825.0,Single,Female,120000,5.0,Partial College,Professional,Yes,3,1.0,Europe,54,No
6996,22826.0,Married,Male,130000,5.0,High School,Professional,Yes,3,2.0,Europe,54,No